### ISSUE TITLE
Incompatibility between hiddengraphs and categories plugin

### ISSUE THREAD

**Issue by toussa** [markrcote/flot-hiddengraphs#3]
Hi.
I found something strange. It seems there is an incompatibility between categories plugin (v1.0) and the hiddengraphs plugin (v1.0).
Actually, i tried to run the categories example without changing anything except adding hiddengraphs file (I didn't even touch the code).

Here is the error in the javascript console:
" Uncaught TypeError: Cannot read property 'x' of null "

After a deep look, the problem is located in hiddengraphs.js, in the function

``` javascript
 function hideDatapointsIfNecessary(plot, s, datapoints) {
            if (!s.points.show && !s.lines.show) {
                s.datapoints.format = [ null, null ];
            }
        }
```

It sets to null the format array, and then, when it's the turn of categories, it failed on : 

``` javascript
function transformPointsOnAxis(datapoints, axis, categories) {
       ...
//HERE, format[0]["x"]  => null["x"]
                if (val == null || !format[m][formatColumn])
                    continue;
...
    }
```

a solution to this would be to add a test if "hideable" is set to true:

``` javascript
function hideDatapointsIfNecessary(plot, s, datapoints) {
            //PATCH: adding a test to see if hideable is set to true
            if(!plot.getOptions().legend.hideable)
                return;

            if (!s.points.show && !s.lines.show) {
                s.datapoints.format = [ null, null ];
            }

        }
```

It does the trick !

PS: I posted here too https://github.com/flot/flot/issues/960

**Comment by markrcote** [comment]
The README clearly says that this plugin works only with line (and, very recently, point) graphs. However, you are right that this function should be doing nothing if options.legend.hideable is false. Thanks!
